version: '3.8'

services:
  web:
    build: .
    # İçeride Django yine 8000'den yayın yapıyor, onu bozma
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      # SOL Taraf: Dışarıdan gireceğin port (8001)
      # SAĞ Taraf: İçerideki port (8000)
      - "8005:8000"