version: '3.8'

services:
  web:
    build: .
    # Konteyner açılırken önce veritabanını oluşturur, sonra sunucuyu 8000'den başlatır
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    # Port çakışması olmasın diye 8005 yapmışsın, aynen kalsın
    ports:
      - "8005:8000"