version: '3.8'

services:
  web:
    build: .
    # Konteyner ölmesin diye boş boş bekletiyoruz
    command: tail -f /dev/null
    volumes:
      - .:/app
      - /app/frontend
    ports:
      - "8005:8000"